# Generated by Django 6.0.3 on 2026-03-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='phone',
            field=models.CharField(max_length=17),
        ),
    ]
