# Generated by Django 6.0.3 on 2026-03-10 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_studentmodel_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
