# Generated by Django 6.0.3 on 2026-03-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_create_at_studentmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
